// lib/mockData/disputeData.ts
import { DisputeCase } from '@/types/admin';

export const mockDisputeCases: DisputeCase[] = [
  {
    id: 'dispute-001',
    caseNumber: 'DS-2024-001',
    transactionId: 'txn-002',
    auctionId: 'auction-7890',
    auctionTitle: '2020 Toyota Camry SE - One Owner',
    initiatedBy: 'user-3003',
    initiatorName: 'Lisa Martinez',
    respondent: 'user-3004',
    respondentName: 'Private Seller',
    category: 'vehicle_condition',
    priority: 'high',
    status: 'investigating',
    createdAt: '2024-01-16T16:00:00Z',
    updatedAt: '2024-01-17T10:30:00Z',
    description: 'Vehicle received with undisclosed damage. Buyer reports scratches on passenger door, small dent on hood, and interior smells of smoke despite listing stating non-smoker vehicle. These issues were not mentioned in the original listing.',
    evidence: {
      documents: [
        '/disputes/ds-001-listing-original.pdf',
        '/disputes/ds-001-condition-report.pdf',
      ],
      photos: [
        '/disputes/ds-001-scratch-1.jpg',
        '/disputes/ds-001-scratch-2.jpg',
        '/disputes/ds-001-dent-hood.jpg',
        '/disputes/ds-001-interior-1.jpg',
      ],
      videos: ['/disputes/ds-001-walkthrough.mp4'],
      messages: [
        '/disputes/ds-001-buyer-seller-chat.pdf',
        '/disputes/ds-001-email-thread.pdf',
      ],
    },
    timeline: [
      {
        id: 'evt-001',
        type: 'created',
        description: 'Dispute case opened by buyer',
        timestamp: '2024-01-16T16:00:00Z',
        actor: 'user-3003',
        actorName: 'Lisa Martinez',
      },
      {
        id: 'evt-002',
        type: 'evidence_added',
        description: 'Buyer uploaded photos of damage',
        timestamp: '2024-01-16T16:15:00Z',
        actor: 'user-3003',
        actorName: 'Lisa Martinez',
      },
      {
        id: 'evt-003',
        type: 'assigned',
        description: 'Case assigned to admin team',
        timestamp: '2024-01-16T17:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
      {
        id: 'evt-004',
        type: 'message',
        description: 'Seller responded with explanation',
        timestamp: '2024-01-17T09:00:00Z',
        actor: 'user-3004',
        actorName: 'Private Seller',
      },
      {
        id: 'evt-005',
        type: 'updated',
        description: 'Status changed to investigating',
        timestamp: '2024-01-17T10:30:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
    ],
    assignedTo: 'admin-789',
  },
  {
    id: 'dispute-002',
    caseNumber: 'DS-2024-002',
    transactionId: 'txn-006',
    auctionId: 'auction-7912',
    auctionTitle: '2019 Jeep Wrangler Unlimited - 4x4',
    initiatedBy: 'user-4001',
    initiatorName: 'Robert Johnson',
    respondent: 'user-4002',
    respondentName: 'Adventure Auto Sales',
    category: 'payment',
    priority: 'urgent',
    status: 'open',
    createdAt: '2024-01-17T14:00:00Z',
    updatedAt: '2024-01-17T14:00:00Z',
    description: 'Seller claims payment was not received despite buyer providing bank transfer confirmation. Amount: $35,000. Buyer has proof of successful transfer but seller states funds never arrived in their account.',
    evidence: {
      documents: [
        '/disputes/ds-002-bank-transfer.pdf',
        '/disputes/ds-002-confirmation-email.pdf',
      ],
      photos: ['/disputes/ds-002-receipt.jpg'],
      videos: [],
      messages: ['/disputes/ds-002-communication.pdf'],
    },
    timeline: [
      {
        id: 'evt-006',
        type: 'created',
        description: 'Dispute case opened by seller',
        timestamp: '2024-01-17T14:00:00Z',
        actor: 'user-4002',
        actorName: 'Adventure Auto Sales',
      },
    ],
  },
  {
    id: 'dispute-003',
    caseNumber: 'DS-2024-003',
    transactionId: 'txn-007',
    auctionId: 'auction-7834',
    auctionTitle: '2018 BMW 3 Series - Sport Package',
    initiatedBy: 'user-4003',
    initiatorName: 'Sarah Williams',
    respondent: 'user-4004',
    respondentName: 'Elite Motors LLC',
    category: 'fraud',
    priority: 'urgent',
    status: 'escalated',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-16T15:00:00Z',
    description: 'Buyer suspects VIN tampering and title fraud. VIN on vehicle does not match VIN in listing. Title shows salvage status but was advertised as clean title. Multiple red flags detected.',
    evidence: {
      documents: [
        '/disputes/ds-003-title-document.pdf',
        '/disputes/ds-003-vin-inspection.pdf',
        '/disputes/ds-003-carfax-report.pdf',
      ],
      photos: [
        '/disputes/ds-003-vin-plate-1.jpg',
        '/disputes/ds-003-vin-plate-2.jpg',
        '/disputes/ds-003-title-photo.jpg',
      ],
      videos: ['/disputes/ds-003-inspection-video.mp4'],
      messages: [],
    },
    timeline: [
      {
        id: 'evt-007',
        type: 'created',
        description: 'Dispute case opened by buyer',
        timestamp: '2024-01-15T10:00:00Z',
        actor: 'user-4003',
        actorName: 'Sarah Williams',
      },
      {
        id: 'evt-008',
        type: 'assigned',
        description: 'Case assigned to fraud investigation team',
        timestamp: '2024-01-15T11:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
      {
        id: 'evt-009',
        type: 'escalated',
        description: 'Case escalated to senior dispute panel due to fraud suspicion',
        timestamp: '2024-01-16T15:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
    ],
    assignedTo: 'admin-789',
  },
  {
    id: 'dispute-004',
    caseNumber: 'DS-2024-004',
    transactionId: 'txn-008',
    auctionId: 'auction-7901',
    auctionTitle: '2021 Mazda CX-5 Touring',
    initiatedBy: 'user-4005',
    initiatorName: 'Michael Brown',
    respondent: 'user-4006',
    respondentName: 'Quick Sale Cars',
    category: 'delivery',
    priority: 'medium',
    status: 'resolved',
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-01-14T16:00:00Z',
    description: 'Vehicle was not delivered on agreed date. Seller claimed shipping delays, buyer requested compensation for additional rental car costs.',
    evidence: {
      documents: ['/disputes/ds-004-rental-receipts.pdf'],
      photos: [],
      videos: [],
      messages: ['/disputes/ds-004-messages.pdf'],
    },
    timeline: [
      {
        id: 'evt-010',
        type: 'created',
        description: 'Dispute case opened by buyer',
        timestamp: '2024-01-12T09:00:00Z',
        actor: 'user-4005',
        actorName: 'Michael Brown',
      },
      {
        id: 'evt-011',
        type: 'assigned',
        description: 'Case assigned to dispute team',
        timestamp: '2024-01-12T10:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
      {
        id: 'evt-012',
        type: 'message',
        description: 'Parties agreed to settlement',
        timestamp: '2024-01-14T14:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
      {
        id: 'evt-013',
        type: 'resolved',
        description: 'Case resolved with partial refund to buyer',
        timestamp: '2024-01-14T16:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
    ],
    assignedTo: 'admin-789',
    resolution: {
      decision: 'Seller agreed to compensate buyer for 3 days of rental car costs',
      refundAmount: 450,
      action: 'Partial refund processed',
      resolvedBy: 'admin-789',
      resolvedAt: '2024-01-14T16:00:00Z',
    },
  },
  {
    id: 'dispute-005',
    caseNumber: 'DS-2023-127',
    transactionId: 'txn-009',
    auctionId: 'auction-7756',
    auctionTitle: '2017 Honda Accord EX - Certified',
    initiatedBy: 'user-4007',
    initiatorName: 'Jennifer Davis',
    respondent: 'user-4008',
    respondentName: 'Hometown Auto',
    category: 'vehicle_condition',
    priority: 'high',
    status: 'escalated',
    createdAt: '2024-01-10T11:00:00Z',
    updatedAt: '2024-01-15T09:00:00Z',
    description: 'Major mechanical issues discovered post-delivery. Engine warning light came on within 24 hours. Independent inspection revealed transmission problems not disclosed in listing. Requesting full refund.',
    evidence: {
      documents: [
        '/disputes/ds-005-inspection-report.pdf',
        '/disputes/ds-005-mechanic-quote.pdf',
      ],
      photos: [
        '/disputes/ds-005-warning-light.jpg',
        '/disputes/ds-005-engine-bay.jpg',
      ],
      videos: ['/disputes/ds-005-test-drive.mp4'],
      messages: ['/disputes/ds-005-communication.pdf'],
    },
    timeline: [
      {
        id: 'evt-014',
        type: 'created',
        description: 'Dispute case opened by buyer',
        timestamp: '2024-01-10T11:00:00Z',
        actor: 'user-4007',
        actorName: 'Jennifer Davis',
      },
      {
        id: 'evt-015',
        type: 'evidence_added',
        description: 'Buyer submitted mechanic inspection report',
        timestamp: '2024-01-11T14:00:00Z',
        actor: 'user-4007',
        actorName: 'Jennifer Davis',
      },
      {
        id: 'evt-016',
        type: 'assigned',
        description: 'Case assigned to senior panel',
        timestamp: '2024-01-12T09:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
      {
        id: 'evt-017',
        type: 'message',
        description: 'Seller disputed claims, provided maintenance records',
        timestamp: '2024-01-13T16:00:00Z',
        actor: 'user-4008',
        actorName: 'Hometown Auto',
      },
      {
        id: 'evt-018',
        type: 'escalated',
        description: 'Case escalated due to conflicting evidence and high amount',
        timestamp: '2024-01-15T09:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
    ],
    assignedTo: 'admin-789',
  },
  {
    id: 'dispute-006',
    caseNumber: 'DS-2024-006',
    transactionId: 'txn-010',
    auctionId: 'auction-7945',
    auctionTitle: '2022 Tesla Model 3 - Long Range',
    initiatedBy: 'user-4009',
    initiatorName: 'David Lee',
    respondent: 'user-4010',
    respondentName: 'EV Dealership Pro',
    category: 'payment',
    priority: 'low',
    status: 'resolved',
    createdAt: '2024-01-16T08:00:00Z',
    updatedAt: '2024-01-16T18:00:00Z',
    description: 'Minor payment processing delay. Buyer reported double charge, issue resolved within same day by payment gateway.',
    evidence: {
      documents: ['/disputes/ds-006-bank-statement.pdf'],
      photos: [],
      videos: [],
      messages: [],
    },
    timeline: [
      {
        id: 'evt-019',
        type: 'created',
        description: 'Dispute opened for payment issue',
        timestamp: '2024-01-16T08:00:00Z',
        actor: 'user-4009',
        actorName: 'David Lee',
      },
      {
        id: 'evt-020',
        type: 'resolved',
        description: 'Duplicate charge reversed by payment processor',
        timestamp: '2024-01-16T18:00:00Z',
        actor: 'admin-789',
        actorName: 'Michael Chen',
      },
    ],
    assignedTo: 'admin-789',
    resolution: {
      decision: 'Payment gateway error confirmed. Duplicate charge reversed.',
      refundAmount: 45000,
      action: 'Automatic reversal processed',
      resolvedBy: 'admin-789',
      resolvedAt: '2024-01-16T18:00:00Z',
    },
  },
];
