// lib/mockData/fraudData.ts
import { FraudAlert, AuditLog } from '@/types/admin';

export const mockFraudAlerts: FraudAlert[] = [
  {
    id: 'fraud-001',
    userId: 'user-007',
    userName: 'David Brown',
    userEmail: 'david.brown@example.com',
    type: 'suspicious_pattern',
    severity: 'critical',
    status: 'investigating',
    detectedAt: '2024-01-18T10:30:00Z',
    description: 'Multiple failed payment attempts from different payment methods within 24 hours',
    indicators: [
      '5 failed payments in 24 hours',
      '3 different credit cards used',
      'IP address changed 4 times',
      'VPN usage detected',
    ],
    ipAddresses: ['192.168.1.100', '10.0.0.50', '172.16.0.25', '198.51.100.42'],
    devices: [
      { type: 'desktop', os: 'Windows 11', browser: 'Chrome 120' },
      { type: 'mobile', os: 'Android 14', browser: 'Chrome Mobile' },
      { type: 'desktop', os: 'macOS', browser: 'Safari 17' },
    ],
    relatedUsers: ['user-011', 'user-012'],
    assignedTo: 'admin-789',
    notes: 'Possible account takeover attempt. All payment methods have been temporarily blocked.',
  },
  {
    id: 'fraud-002',
    userId: 'user-005',
    userName: 'Robert Taylor',
    userEmail: 'robert.taylor@example.com',
    type: 'multiple_accounts',
    severity: 'high',
    status: 'open',
    detectedAt: '2024-01-17T15:20:00Z',
    description: 'Suspected of operating multiple seller accounts to manipulate auction visibility',
    indicators: [
      'Same bank account linked to 2 accounts',
      'Similar listing patterns across accounts',
      'Same IP address for account creation',
      'Cross-bidding between accounts detected',
    ],
    ipAddresses: ['203.0.113.45', '203.0.113.47'],
    devices: [
      { type: 'desktop', os: 'Windows 10', browser: 'Firefox 121' },
    ],
    relatedUsers: ['user-013'],
    assignedTo: 'admin-789',
    notes: 'Monitoring both accounts. Awaiting bank verification results.',
  },
  {
    id: 'fraud-003',
    userId: 'user-014',
    userName: 'Thomas Johnson',
    userEmail: 'thomas.johnson@example.com',
    type: 'document_fraud',
    severity: 'critical',
    status: 'resolved',
    detectedAt: '2024-01-15T09:00:00Z',
    resolvedAt: '2024-01-16T14:30:00Z',
    description: 'Submitted falsified identity documents during KYC verification',
    indicators: [
      'Document metadata shows recent creation date',
      'Photo inconsistencies detected by AI',
      'ID number format invalid for claimed state',
      'Address verification failed',
    ],
    ipAddresses: ['198.18.0.25'],
    devices: [
      { type: 'mobile', os: 'iOS 17', browser: 'Safari Mobile' },
    ],
    relatedUsers: [],
    assignedTo: 'admin-789',
    resolution: 'Account permanently banned. Documents forwarded to legal team. Law enforcement notified.',
    notes: 'Clear case of identity fraud. User attempted to appeal but provided no valid documentation.',
  },
  {
    id: 'fraud-004',
    userId: 'user-015',
    userName: 'Patricia Lee',
    userEmail: 'patricia.lee@example.com',
    type: 'payment_fraud',
    severity: 'high',
    status: 'investigating',
    detectedAt: '2024-01-18T08:15:00Z',
    description: 'Chargeback pattern detected - won 4 auctions, paid, received vehicles, then initiated chargebacks',
    indicators: [
      '4 chargebacks in 2 weeks',
      'All vehicles delivered with proof',
      'User claimed "unauthorized transactions"',
      'Pattern matches known fraud scheme',
    ],
    ipAddresses: ['192.0.2.146'],
    devices: [
      { type: 'desktop', os: 'macOS', browser: 'Chrome 120' },
    ],
    relatedUsers: [],
    assignedTo: 'admin-789',
    notes: 'Coordinating with payment processor and sellers. Evidence package being prepared for dispute.',
  },
  {
    id: 'fraud-005',
    userId: 'user-016',
    userName: 'Christopher Martin',
    userEmail: 'christopher.martin@example.com',
    type: 'suspicious_pattern',
    severity: 'medium',
    status: 'monitoring',
    detectedAt: '2024-01-16T12:00:00Z',
    description: 'Unusual bidding behavior - consistent last-second bids across multiple auctions',
    indicators: [
      'Bot-like bidding pattern detected',
      '15 bids placed in final 5 seconds',
      'Consistent timing across auctions',
      'No manual browsing activity detected',
    ],
    ipAddresses: ['198.51.100.78'],
    devices: [
      { type: 'desktop', os: 'Ubuntu Linux', browser: 'Firefox 121' },
    ],
    relatedUsers: [],
    notes: 'Possible auction sniping bot. Monitoring for Terms of Service violations.',
  },
  {
    id: 'fraud-006',
    userId: 'user-004',
    userName: 'Lisa Martinez',
    userEmail: 'lisa.martinez@example.com',
    type: 'suspicious_pattern',
    severity: 'medium',
    status: 'resolved',
    detectedAt: '2024-01-14T11:30:00Z',
    resolvedAt: '2024-01-16T10:00:00Z',
    description: 'Repeated payment delays and communication issues with sellers',
    indicators: [
      '3 payment delays over 48 hours',
      'Unresponsive to seller messages',
      'Multiple excuses for payment issues',
      'Low trust score trend',
    ],
    ipAddresses: ['203.0.113.89'],
    devices: [
      { type: 'mobile', os: 'Android 13', browser: 'Chrome Mobile' },
    ],
    relatedUsers: [],
    assignedTo: 'admin-789',
    resolution: 'Account suspended for 30 days. User must complete payment training module before reactivation.',
    notes: 'User acknowledged issues and agreed to suspension. Not malicious, just disorganized.',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    timestamp: '2024-01-18T16:45:00Z',
    actor: 'admin-789',
    actorName: 'Michael Chen',
    actorRole: 'admin',
    action: 'user_suspended',
    resource: 'user-004',
    resourceType: 'user',
    details: {
      reason: 'Multiple payment disputes and late payments',
      duration: '30 days',
      previousStatus: 'active',
      newStatus: 'suspended',
    },
    ipAddress: '192.0.2.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    id: 'audit-002',
    timestamp: '2024-01-18T15:30:00Z',
    actor: 'admin-789',
    actorName: 'Michael Chen',
    actorRole: 'admin',
    action: 'kyc_approved',
    resource: 'kyc-012',
    resourceType: 'kyc_application',
    details: {
      userId: 'user-017',
      userName: 'Amanda White',
      verificationLevel: 'full',
      documentTypes: ['drivers_license', 'proof_of_address'],
    },
    ipAddress: '192.0.2.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    id: 'audit-003',
    timestamp: '2024-01-18T14:15:00Z',
    actor: 'moderator-456',
    actorName: 'Sarah Johnson',
    actorRole: 'moderator',
    action: 'listing_removed',
    resource: 'auction-8901',
    resourceType: 'listing',
    details: {
      reason: 'Violated listing policy - misleading title',
      sellerId: 'user-018',
      sellerName: 'Quick Auto Sales',
      refundIssued: true,
    },
    ipAddress: '192.0.2.11',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
  },
  {
    id: 'audit-004',
    timestamp: '2024-01-18T13:00:00Z',
    actor: 'admin-789',
    actorName: 'Michael Chen',
    actorRole: 'admin',
    action: 'escrow_released',
    resource: 'escrow-056',
    resourceType: 'escrow',
    details: {
      amount: 35000,
      transactionId: 'txn-234',
      reason: 'Successful delivery confirmed by both parties',
      recipientId: 'user-005',
    },
    ipAddress: '192.0.2.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    id: 'audit-005',
    timestamp: '2024-01-18T11:45:00Z',
    actor: 'admin-789',
    actorName: 'Michael Chen',
    actorRole: 'admin',
    action: 'trust_score_adjusted',
    resource: 'user-003',
    resourceType: 'user',
    details: {
      previousScore: 82,
      newScore: 78,
      reason: 'Late delivery warning issued',
      adjustment: -4,
    },
    ipAddress: '192.0.2.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    id: 'audit-006',
    timestamp: '2024-01-18T10:30:00Z',
    actor: 'admin-789',
    actorName: 'Michael Chen',
    actorRole: 'admin',
    action: 'feature_flag_toggled',
    resource: 'instant_buy',
    resourceType: 'feature_flag',
    details: {
      previousState: false,
      newState: true,
      rolloutPercentage: 25,
      targetSegment: 'trusted_users',
    },
    ipAddress: '192.0.2.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    id: 'audit-007',
    timestamp: '2024-01-18T09:15:00Z',
    actor: 'admin-789',
    actorName: 'Michael Chen',
    actorRole: 'admin',
    action: 'dispute_resolved',
    resource: 'dispute-004',
    resourceType: 'dispute',
    details: {
      caseNumber: 'DS-2024-004',
      decision: 'Partial refund to buyer',
      refundAmount: 450,
      inFavorOf: 'buyer',
    },
    ipAddress: '192.0.2.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    id: 'audit-008',
    timestamp: '2024-01-17T18:00:00Z',
    actor: 'admin-789',
    actorName: 'Michael Chen',
    actorRole: 'admin',
    action: 'emergency_freeze_activated',
    resource: 'platform',
    resourceType: 'system',
    details: {
      reason: 'Suspected coordinated fraud attack',
      scope: 'new_transactions',
      duration: '2 hours',
      affectedUsers: 0,
    },
    ipAddress: '192.0.2.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    id: 'audit-009',
    timestamp: '2024-01-17T17:30:00Z',
    actor: 'admin-789',
    actorName: 'Michael Chen',
    actorRole: 'admin',
    action: 'user_locked',
    resource: 'user-007',
    resourceType: 'user',
    details: {
      reason: 'Fraudulent activity detected - permanent ban',
      previousStatus: 'flagged',
      newStatus: 'locked',
      evidenceFiled: true,
    },
    ipAddress: '192.0.2.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    id: 'audit-010',
    timestamp: '2024-01-17T16:00:00Z',
    actor: 'moderator-456',
    actorName: 'Sarah Johnson',
    actorRole: 'moderator',
    action: 'support_ticket_resolved',
    resource: 'ticket-1001',
    resourceType: 'support_ticket',
    details: {
      category: 'technical',
      resolutionTime: '2.5 hours',
      satisfaction: 'high',
      userId: 'user-009',
    },
    ipAddress: '192.0.2.11',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
  },
];
