// lib/mockData/transactionData.ts
import {
  KYCApplication,
  SupportTicket,
  TransactionReview,
  EscrowTransaction,
  PaymentLog,
} from '@/types/admin';

// KYC Applications Mock Data
export const mockKYCApplications: KYCApplication[] = [
  {
    id: 'kyc-001',
    userId: 'user-1001',
    userName: 'John Smith',
    userEmail: 'john.smith@email.com',
    submittedAt: '2024-01-15T10:30:00Z',
    status: 'pending',
    documents: {
      idFront: '/documents/id-front-001.jpg',
      idBack: '/documents/id-back-001.jpg',
      selfie: '/documents/selfie-001.jpg',
      proofOfAddress: '/documents/address-001.pdf',
    },
    personalInfo: {
      fullName: 'John Michael Smith',
      dateOfBirth: '1990-05-15',
      address: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'United States',
      idNumber: 'DL-NY-12345678',
      idType: 'drivers_license',
    },
    verificationChecks: {
      documentQuality: true,
      faceMatch: true,
      addressVerified: true,
      noFraud: true,
    },
  },
  {
    id: 'kyc-002',
    userId: 'user-1002',
    userName: 'Sarah Johnson',
    userEmail: 'sarah.j@email.com',
    submittedAt: '2024-01-15T11:45:00Z',
    status: 'pending',
    documents: {
      idFront: '/documents/id-front-002.jpg',
      idBack: '/documents/id-back-002.jpg',
      selfie: '/documents/selfie-002.jpg',
    },
    personalInfo: {
      fullName: 'Sarah Elizabeth Johnson',
      dateOfBirth: '1985-08-22',
      address: '456 Oak Avenue',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      country: 'United States',
      idNumber: 'P-USA-87654321',
      idType: 'passport',
    },
    verificationChecks: {
      documentQuality: true,
      faceMatch: true,
      addressVerified: false,
      noFraud: true,
    },
  },
  {
    id: 'kyc-003',
    userId: 'user-1003',
    userName: 'Michael Chen',
    userEmail: 'm.chen@email.com',
    submittedAt: '2024-01-14T15:20:00Z',
    status: 'needs_review',
    documents: {
      idFront: '/documents/id-front-003.jpg',
      idBack: '/documents/id-back-003.jpg',
      selfie: '/documents/selfie-003.jpg',
      proofOfAddress: '/documents/address-003.pdf',
    },
    personalInfo: {
      fullName: 'Michael Chen',
      dateOfBirth: '1992-11-30',
      address: '789 Pine Street',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'United States',
      idNumber: 'DL-IL-98765432',
      idType: 'drivers_license',
    },
    verificationChecks: {
      documentQuality: false,
      faceMatch: true,
      addressVerified: true,
      noFraud: true,
    },
    notes: 'ID document quality is poor, requesting better photo',
  },
  {
    id: 'kyc-004',
    userId: 'user-1004',
    userName: 'Emily Rodriguez',
    userEmail: 'emily.r@email.com',
    submittedAt: '2024-01-13T09:15:00Z',
    status: 'approved',
    reviewedBy: 'mod-456',
    reviewedAt: '2024-01-13T14:30:00Z',
    documents: {
      idFront: '/documents/id-front-004.jpg',
      idBack: '/documents/id-back-004.jpg',
      selfie: '/documents/selfie-004.jpg',
      proofOfAddress: '/documents/address-004.pdf',
    },
    personalInfo: {
      fullName: 'Emily Marie Rodriguez',
      dateOfBirth: '1988-03-10',
      address: '321 Elm Drive',
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
      country: 'United States',
      idNumber: 'DL-FL-45678912',
      idType: 'drivers_license',
    },
    verificationChecks: {
      documentQuality: true,
      faceMatch: true,
      addressVerified: true,
      noFraud: true,
    },
  },
  {
    id: 'kyc-005',
    userId: 'user-1005',
    userName: 'David Wilson',
    userEmail: 'd.wilson@email.com',
    submittedAt: '2024-01-12T16:40:00Z',
    status: 'rejected',
    reviewedBy: 'mod-456',
    reviewedAt: '2024-01-13T10:20:00Z',
    documents: {
      idFront: '/documents/id-front-005.jpg',
      idBack: '/documents/id-back-005.jpg',
      selfie: '/documents/selfie-005.jpg',
    },
    personalInfo: {
      fullName: 'David Wilson',
      dateOfBirth: '1995-07-18',
      address: '567 Maple Court',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      country: 'United States',
      idNumber: 'DL-WA-78945612',
      idType: 'drivers_license',
    },
    verificationChecks: {
      documentQuality: true,
      faceMatch: false,
      addressVerified: false,
      noFraud: false,
    },
    rejectionReason: 'Face verification failed and suspicious activity detected',
  },
];

// Support Tickets Mock Data
export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'ticket-001',
    ticketNumber: 'TKT-4521',
    userId: 'user-2001',
    userName: 'Alice Brown',
    userEmail: 'alice.brown@email.com',
    subject: 'Payment not received after auction win',
    category: 'payment',
    priority: 'high',
    status: 'open',
    createdAt: '2024-01-15T14:30:00Z',
    updatedAt: '2024-01-15T14:30:00Z',
    messages: [
      {
        id: 'msg-001',
        senderId: 'user-2001',
        senderName: 'Alice Brown',
        senderType: 'user',
        message: 'I won auction #7845 two days ago and paid immediately, but the seller hasn\'t confirmed receiving payment. Can you help?',
        timestamp: '2024-01-15T14:30:00Z',
      },
    ],
  },
  {
    id: 'ticket-002',
    ticketNumber: 'TKT-4522',
    userId: 'user-2002',
    userName: 'Robert Taylor',
    userEmail: 'robert.t@email.com',
    subject: 'Cannot access my account',
    category: 'account',
    priority: 'urgent',
    status: 'in_progress',
    createdAt: '2024-01-15T09:15:00Z',
    updatedAt: '2024-01-15T13:20:00Z',
    assignedTo: 'mod-456',
    messages: [
      {
        id: 'msg-002',
        senderId: 'user-2002',
        senderName: 'Robert Taylor',
        senderType: 'user',
        message: 'I\'ve been locked out of my account for 3 hours. I need access urgently as I have an active auction ending soon.',
        timestamp: '2024-01-15T09:15:00Z',
      },
      {
        id: 'msg-003',
        senderId: 'mod-456',
        senderName: 'Sarah Wilson',
        senderType: 'moderator',
        message: 'Hello Robert, I\'m looking into this issue. Can you confirm your registered email address and when you last successfully logged in?',
        timestamp: '2024-01-15T10:30:00Z',
      },
      {
        id: 'msg-004',
        senderId: 'user-2002',
        senderName: 'Robert Taylor',
        senderType: 'user',
        message: 'My email is robert.t@email.com and I last logged in yesterday evening around 8 PM.',
        timestamp: '2024-01-15T11:00:00Z',
      },
    ],
  },
  {
    id: 'ticket-003',
    ticketNumber: 'TKT-4523',
    userId: 'user-2003',
    userName: 'Jennifer Lee',
    userEmail: 'jennifer.lee@email.com',
    subject: 'Incorrect vehicle description',
    category: 'auction',
    priority: 'medium',
    status: 'waiting_response',
    createdAt: '2024-01-14T16:45:00Z',
    updatedAt: '2024-01-15T09:00:00Z',
    assignedTo: 'mod-456',
    messages: [
      {
        id: 'msg-005',
        senderId: 'user-2003',
        senderName: 'Jennifer Lee',
        senderType: 'user',
        message: 'The vehicle I received doesn\'t match the listing description. The ad said it had 45,000 miles but the odometer shows 78,000.',
        timestamp: '2024-01-14T16:45:00Z',
      },
      {
        id: 'msg-006',
        senderId: 'mod-456',
        senderName: 'Sarah Wilson',
        senderType: 'moderator',
        message: 'Thank you for reporting this. Can you please provide photos of the odometer and the original listing? This is a serious issue that we\'ll investigate immediately.',
        timestamp: '2024-01-15T09:00:00Z',
      },
    ],
  },
  {
    id: 'ticket-004',
    ticketNumber: 'TKT-4520',
    userId: 'user-2004',
    userName: 'Mark Anderson',
    userEmail: 'mark.a@email.com',
    subject: 'Website loading slowly',
    category: 'technical',
    priority: 'low',
    status: 'resolved',
    createdAt: '2024-01-13T11:20:00Z',
    updatedAt: '2024-01-14T15:30:00Z',
    assignedTo: 'mod-456',
    messages: [
      {
        id: 'msg-007',
        senderId: 'user-2004',
        senderName: 'Mark Anderson',
        senderType: 'user',
        message: 'The website has been loading very slowly for the past hour. Is there a technical issue?',
        timestamp: '2024-01-13T11:20:00Z',
      },
      {
        id: 'msg-008',
        senderId: 'mod-456',
        senderName: 'Sarah Wilson',
        senderType: 'moderator',
        message: 'We had a temporary server issue that has now been resolved. Please try clearing your browser cache. Let us know if you continue experiencing issues.',
        timestamp: '2024-01-13T14:00:00Z',
      },
      {
        id: 'msg-009',
        senderId: 'user-2004',
        senderName: 'Mark Anderson',
        senderType: 'user',
        message: 'Everything is working perfectly now. Thank you!',
        timestamp: '2024-01-14T15:30:00Z',
      },
    ],
  },
];

// Transaction Reviews Mock Data
export const mockTransactionReviews: TransactionReview[] = [
  {
    id: 'txn-001',
    auctionId: 'auction-7845',
    auctionTitle: '2018 Honda Civic LX - Low Miles',
    buyerId: 'user-3001',
    buyerName: 'Tom Harris',
    sellerId: 'user-3002',
    sellerName: 'Auto Dealer Inc',
    amount: 18500,
    agreedTerms: {
      price: 18500,
      pickupDate: '2024-01-20',
      pickupLocation: '123 Dealer Street, Boston, MA',
      paymentMethod: 'Escrow',
      shippingMethod: 'pickup',
      additionalNotes: 'Buyer will inspect vehicle before payment release',
    },
    status: 'pending',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'txn-002',
    auctionId: 'auction-7890',
    auctionTitle: '2020 Toyota Camry SE - One Owner',
    buyerId: 'user-3003',
    buyerName: 'Lisa Martinez',
    sellerId: 'user-3004',
    sellerName: 'Private Seller',
    amount: 24000,
    agreedTerms: {
      price: 24000,
      pickupDate: '2024-01-18',
      pickupLocation: '456 Home Drive, Austin, TX',
      paymentMethod: 'Escrow',
      shippingMethod: 'delivery',
      additionalNotes: 'Seller will arrange shipping to buyer location',
    },
    status: 'approved',
    createdAt: '2024-01-14T15:30:00Z',
    reviewedBy: 'mod-456',
    reviewedAt: '2024-01-14T16:00:00Z',
  },
  {
    id: 'txn-003',
    auctionId: 'auction-7923',
    auctionTitle: '2019 Ford F-150 XLT - Clean Title',
    buyerId: 'user-3005',
    buyerName: 'Kevin White',
    sellerId: 'user-3006',
    sellerName: 'Truck World LLC',
    amount: 32000,
    agreedTerms: {
      price: 32000,
      pickupDate: '2024-01-25',
      pickupLocation: '789 Truck Lot, Denver, CO',
      paymentMethod: 'Escrow',
      shippingMethod: 'pickup',
    },
    status: 'completed',
    createdAt: '2024-01-10T09:00:00Z',
    reviewedBy: 'admin-789',
    reviewedAt: '2024-01-10T10:00:00Z',
  },
];

// Escrow Transactions Mock Data
export const mockEscrowTransactions: EscrowTransaction[] = [
  {
    id: 'escrow-001',
    transactionId: 'txn-001',
    auctionId: 'auction-7845',
    auctionTitle: '2018 Honda Civic LX - Low Miles',
    buyerId: 'user-3001',
    buyerName: 'Tom Harris',
    sellerId: 'user-3002',
    sellerName: 'Auto Dealer Inc',
    amount: 18500,
    escrowStatus: 'held',
    heldSince: '2024-01-15T12:00:00Z',
    releaseScheduled: '2024-01-20T18:00:00Z',
    notes: 'Awaiting vehicle inspection and buyer confirmation',
  },
  {
    id: 'escrow-002',
    transactionId: 'txn-002',
    auctionId: 'auction-7890',
    auctionTitle: '2020 Toyota Camry SE - One Owner',
    buyerId: 'user-3003',
    buyerName: 'Lisa Martinez',
    sellerId: 'user-3004',
    sellerName: 'Private Seller',
    amount: 24000,
    escrowStatus: 'held',
    heldSince: '2024-01-14T16:00:00Z',
    releaseScheduled: '2024-01-18T15:00:00Z',
  },
  {
    id: 'escrow-003',
    transactionId: 'txn-003',
    auctionId: 'auction-7923',
    auctionTitle: '2019 Ford F-150 XLT - Clean Title',
    buyerId: 'user-3005',
    buyerName: 'Kevin White',
    sellerId: 'user-3006',
    sellerName: 'Truck World LLC',
    amount: 32000,
    escrowStatus: 'released',
    heldSince: '2024-01-10T10:00:00Z',
    releaseScheduled: '2024-01-15T12:00:00Z',
    releaseReason: 'Transaction completed successfully, vehicle delivered',
  },
  {
    id: 'escrow-004',
    transactionId: 'txn-004',
    auctionId: 'auction-7856',
    auctionTitle: '2017 Nissan Altima S - Reliable',
    buyerId: 'user-3007',
    buyerName: 'Amanda Green',
    sellerId: 'user-3008',
    sellerName: 'Quick Sale Motors',
    amount: 15000,
    escrowStatus: 'refunded',
    heldSince: '2024-01-12T09:00:00Z',
    releaseReason: 'Vehicle had undisclosed damage, buyer requested refund',
    notes: 'Seller violated terms, refund approved by admin',
  },
];

// Payment Logs Mock Data
export const mockPaymentLogs: PaymentLog[] = [
  {
    id: 'pay-001',
    transactionId: 'txn-001',
    auctionId: 'auction-7845',
    auctionTitle: '2018 Honda Civic LX',
    buyerId: 'user-3001',
    buyerName: 'Tom Harris',
    sellerId: 'user-3002',
    sellerName: 'Auto Dealer Inc',
    amount: 18500,
    type: 'payment',
    method: 'escrow',
    status: 'completed',
    timestamp: '2024-01-15T12:00:00Z',
    fees: 185,
    netAmount: 18315,
  },
  {
    id: 'pay-002',
    transactionId: 'txn-002',
    auctionId: 'auction-7890',
    auctionTitle: '2020 Toyota Camry SE',
    buyerId: 'user-3003',
    buyerName: 'Lisa Martinez',
    sellerId: 'user-3004',
    sellerName: 'Private Seller',
    amount: 24000,
    type: 'payment',
    method: 'card',
    status: 'processing',
    timestamp: '2024-01-14T16:00:00Z',
    gateway: 'Stripe',
    gatewayTransactionId: 'ch_1234567890',
    fees: 720,
    netAmount: 23280,
  },
  {
    id: 'pay-003',
    transactionId: 'txn-003',
    auctionId: 'auction-7923',
    auctionTitle: '2019 Ford F-150 XLT',
    buyerId: 'user-3005',
    buyerName: 'Kevin White',
    sellerId: 'user-3006',
    sellerName: 'Truck World LLC',
    amount: 32000,
    type: 'payout',
    method: 'bank_transfer',
    status: 'completed',
    timestamp: '2024-01-15T12:30:00Z',
    fees: 50,
    netAmount: 31950,
  },
  {
    id: 'pay-004',
    transactionId: 'txn-004',
    auctionId: 'auction-7856',
    auctionTitle: '2017 Nissan Altima S',
    buyerId: 'user-3007',
    buyerName: 'Amanda Green',
    sellerId: 'user-3008',
    sellerName: 'Quick Sale Motors',
    amount: 15000,
    type: 'refund',
    method: 'escrow',
    status: 'completed',
    timestamp: '2024-01-14T18:00:00Z',
    fees: 0,
    netAmount: 15000,
  },
  {
    id: 'pay-005',
    transactionId: 'txn-005',
    auctionId: 'auction-7901',
    auctionTitle: '2021 Mazda CX-5 Touring',
    buyerId: 'user-3009',
    buyerName: 'Brian Scott',
    sellerId: 'user-3010',
    sellerName: 'Premium Auto Sales',
    amount: 28500,
    type: 'payment',
    method: 'card',
    status: 'failed',
    timestamp: '2024-01-15T08:15:00Z',
    gateway: 'Stripe',
    gatewayTransactionId: 'ch_9876543210',
    fees: 0,
    netAmount: 0,
  },
];
